# Пропишем версию
version: '3.3'
# Перечислим сервисы
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "127.0.0.3:80:80"
            - "127.0.0.3:443:443"
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - /var/www/m2fresh:/var/www/magento2
            - ./nginx/Logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/
        links:
            - php
    mysql:
        image: mysql:5.7
        ports:
            - "127.0.0.3:3306:3306"
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=magento2
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build: ./php
        container_name: php-fpm
        volumes:
          - /var/www/m2fresh:/var/www/magento2
        environment:
          XDEBUG_CONFIG: "remote_host=127.0.0.3 remote_enable=1 remote_autostart=off  remote_port=9000"
        links:
          - mysql