version: '3.3'
services:
    magento2_nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
        depends_on:
            - magento2_php
        volumes:
            - ./nginx/config/:/etc/nginx/conf.d
            - ./nginx/log/:/var/log/nginx/
            - ./project/:/var/www/magento2
        networks:
            magento2-network:
                aliases:
                    - dev.m2test.com
    magento2_php:
        build: ./php
        restart: always
        environment:
            XDEBUG_CONFIG: "remote_port=9001"
        volumes:
            - ./php/config/php.ini:/usr/local/etc/php/php.ini
            - ./project/:/var/www/magento2
        networks:
            - magento2-network
networks:
    magento2-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
#    mysql:
#        image: mysql:5.7
#        volumes:
#            - ./docker/mysql/data:/var/lib/mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#        networks:
#            - backend